services:
  - name: server
    type: web
    buildCommand: npm install && npm run build
    startCommand: node server.js

  - name: client
    type: web
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: cd client && npm start
